/**
 * Generated by scripts/inject_client_config.sh — do not edit by hand.
 * Re-run: ./scripts/inject_client_config.sh <clientId>
 */
export const CLIENT_ID = 'citron' as const
export const CLIENT_DISPLAY_NAME = "Citron CRM Accounting" as const
