#!/usr/bin/env bash
# Inject white-label client config. Usage: ./inject_client_config.sh citron|demo
set -euo pipefail

CLIENT="${1:-citron}"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
APP_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

case "$CLIENT" in
  citron)
    APP_NAME="Citron CRM Accounting"
    ;;
  demo)
    APP_NAME="Accounting (Demo)"
    ;;
  *)
    echo "Unknown client: $CLIENT" >&2
    exit 1
    ;;
esac

echo "Injecting client config: $CLIENT ($APP_NAME)"

echo -n "$CLIENT" > "$APP_ROOT/.vite_client"

CONFIG_OUT="$APP_ROOT/src/config/client-config.generated.ts"
mkdir -p "$(dirname "$CONFIG_OUT")"

DISPLAY_JSON="$(node -e 'console.log(JSON.stringify(process.argv[1]))' "$APP_NAME")"

cat > "$CONFIG_OUT" << EOF
/**
 * Generated by scripts/inject_client_config.sh — do not edit by hand.
 * Re-run: ./scripts/inject_client_config.sh <clientId>
 */
export const CLIENT_ID = '${CLIENT}' as const
export const CLIENT_DISPLAY_NAME = ${DISPLAY_JSON} as const
EOF

echo "Client config injected: $CLIENT"
